# Generated by Django 5.2 on 2025-07-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auth_about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='auth_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
